"use client";

import { useEffect, useRef, useState } from "react";
import { Command, Search, ShieldCheck } from "lucide-react";
import { AuthGate } from "@/components/AuthGate";
import { searchControlData } from "@/lib/control-api";

export default function SearchPage() { return <AuthGate><SearchContent /></AuthGate>; }

function SearchContent() {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<Array<Record<string, unknown>>>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { function shortcut(event: KeyboardEvent) { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); inputRef.current?.focus(); } } window.addEventListener("keydown", shortcut); return () => window.removeEventListener("keydown", shortcut); }, []);
  useEffect(() => { if (query.trim().length < 2) { setResults([]); setLoading(false); return; } const id = window.setTimeout(async () => { setLoading(true); setError(""); try { const response = await searchControlData(query); setResults(response.results); } catch (caught) { setError(caught instanceof Error ? caught.message : "搜尋失敗。"); } finally { setLoading(false); } }, 250); return () => clearTimeout(id); }, [query]);
  return <div className="mx-auto max-w-4xl space-y-5"><section><p className="eyebrow">Command Palette</p><h1 className="page-title mt-1">全域搜尋</h1><p className="muted mt-2 text-sm leading-6">搜尋會在伺服器及資料庫 RLS 先過濾權限，無權查看的標題、數量及 metadata 不會傳到瀏覽器。</p></section><section className="panel overflow-hidden"><label className="relative block border-b border-slate-200"><Search className="pointer-events-none absolute left-4 top-5 h-5 w-5 text-slate-400" /><input ref={inputRef} className="h-16 w-full bg-transparent pl-12 pr-24 text-lg font-semibold outline-none" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋任務、項目、學校、寵物、文件…" autoFocus /><span className="pointer-events-none absolute right-4 top-4 hidden items-center gap-1 rounded-lg border border-slate-200 bg-slate-50 px-2 py-1.5 text-xs font-bold text-slate-500 sm:flex"><Command className="h-3.5 w-3.5" />K</span></label><div className="min-h-64 p-3" aria-live="polite">{loading ? <div className="space-y-2">{[1,2,3].map((item) => <div key={item} className="h-16 animate-pulse rounded-xl bg-slate-100" />)}</div> : error ? <p className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p> : query.trim().length < 2 ? <Empty icon={<Search className="h-5 w-5" />} title="輸入至少兩個字" text="搜尋不會顯示私人 autocomplete 或未授權結果數量。" /> : results.length ? <div className="space-y-2">{results.map((result) => <article key={`${result.resourceType}-${result.id}`} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Search className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{String(result.title)}</p><p className="muted mt-1 text-xs">{typeLabel[String(result.itemType)] || String(result.itemType)} · {areaLabel[String(result.area)] || String(result.area)} · {statusLabel[String(result.status)] || String(result.status)}</p></div>{result.visibility && result.visibility !== "private" ? <span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-bold text-indigo-700">已授權分享</span> : null}</article>)}</div> : <Empty icon={<ShieldCheck className="h-5 w-5" />} title="沒有可查看的結果" text="搜尋不會透露你沒有權限查看的項目是否存在。" />}</div></section></div>;
}
function Empty({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="grid min-h-56 place-items-center text-center"><div><div className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-slate-500">{icon}</div><h2 className="mt-3 font-bold">{title}</h2><p className="muted mt-1 max-w-sm text-sm leading-6">{text}</p></div></div>; }
const typeLabel: Record<string, string> = { task: "任務", project: "項目", waiting: "等待事項", decision: "決策", client: "客戶", sop: "SOP", school: "學校", pet: "寵物", household: "家居", shopping: "購物", health: "健康行政", document: "文件", vehicle: "車輛", note: "私人筆記", event: "日程" };
const areaLabel: Record<string, string> = { work: "工作", family: "家庭", personal: "個人" };
const statusLabel: Record<string, string> = { not_started: "未開始", in_progress: "進行中", waiting: "等待中", blocked: "受阻", done: "已完成", active: "進行中", review: "待檢視", completed: "已完成", cancelled: "已取消", inbox: "收集箱" };
