"use client";

import { useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Plus } from "lucide-react";
import { AuthGate } from "@/components/AuthGate";
import { LoadingState } from "@/components/LoadingState";
import { Modal } from "@/components/Modal";
import { Button } from "@/components/ui/Button";
import { controlAction } from "@/lib/control-api";
import { formatDate } from "@/lib/date";
import { useControlData } from "@/hooks/useControlData";

export default function CalendarPage() { return <AuthGate><CalendarContent /></AuthGate>; }

function CalendarContent() {
  const { data, loading, error, reload } = useControlData(); const [cursor, setCursor] = useState(() => new Date()); const [adding, setAdding] = useState(false);
  const events = useMemo(() => { if (!data) return []; return [...data.tasks.filter((item) => item.due_date).map((item) => ({ id: item.id, date: item.due_date!, title: item.title, area: item.area || (item.scope === "company" ? "work" : "family"), kind: "任務", privacy: "full" })), ...data.operatingItems.filter((item) => item.due_date).map((item) => ({ id: item.id, date: item.due_date!, title: item.metadata.calendarPrivacy === "busy" && item.owner_id !== data.currentUser.id ? "忙碌" : item.title, area: item.area, kind: item.item_type === "event" ? "日程" : "項目", privacy: String(item.metadata.calendarPrivacy || "full") }))].sort((a, b) => a.date.localeCompare(b.date)); }, [data]);
  if (loading || error || !data) return <LoadingState error={error} />;
  const year = cursor.getFullYear(), month = cursor.getMonth(); const first = new Date(year, month, 1); const last = new Date(year, month + 1, 0); const cells = Array.from({ length: first.getDay() + last.getDate() }, (_, index) => index < first.getDay() ? null : index - first.getDay() + 1);
  const monthPrefix = `${year}-${String(month + 1).padStart(2, "0")}`; const monthEvents = events.filter((event) => event.date.startsWith(monthPrefix));
  return <div className="space-y-5"><section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Calendar</p><h1 className="page-title mt-1">日曆</h1><p className="muted mt-2 text-sm leading-6">只顯示你擁有、明確分享、已接受指派或已同意共同管理的日期。</p></div><Button onClick={() => setAdding(true)}><Plus className="h-5 w-5" />新增日程</Button></section>
    <section className="panel overflow-hidden"><header className="flex items-center justify-between border-b border-slate-200 p-4"><button className="icon-button" onClick={() => setCursor(new Date(year, month - 1, 1))} aria-label="上個月"><ChevronLeft className="h-5 w-5" /></button><h2 className="text-lg font-bold">{year} 年 {month + 1} 月</h2><button className="icon-button" onClick={() => setCursor(new Date(year, month + 1, 1))} aria-label="下個月"><ChevronRight className="h-5 w-5" /></button></header><div className="hidden grid-cols-7 border-b border-slate-200 text-center text-xs font-bold text-slate-500 sm:grid">{"日一二三四五六".split("").map((day) => <div key={day} className="py-2">{day}</div>)}</div><div className="hidden grid-cols-7 sm:grid">{cells.map((day, index) => { const date = day ? `${monthPrefix}-${String(day).padStart(2, "0")}` : ""; const dayEvents = monthEvents.filter((event) => event.date === date); return <div key={index} className="min-h-28 border-b border-r border-slate-100 p-2">{day ? <><p className="text-xs font-bold text-slate-500">{day}</p><div className="mt-1 space-y-1">{dayEvents.slice(0, 3).map((event) => <div key={`${event.kind}-${event.id}`} className={`truncate rounded-md px-2 py-1 text-xs font-semibold ${event.area === "work" ? "bg-indigo-50 text-indigo-700" : event.area === "family" ? "bg-blue-50 text-blue-700" : "bg-teal-50 text-teal-700"}`}>{event.title}</div>)}</div></> : null}</div>; })}</div><div className="divide-y divide-slate-100 sm:hidden">{monthEvents.length ? monthEvents.map((event) => <div key={`${event.kind}-${event.id}`} className="flex gap-3 p-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-slate-100 text-sm font-bold">{event.date.slice(8)}</div><div><p className="font-semibold">{event.title}</p><p className="muted mt-1 text-xs">{formatDate(event.date)} · {event.kind}</p></div></div>) : <p className="p-6 text-center text-sm text-slate-500">本月沒有日程。</p>}</div></section>
    {adding ? <EventModal onClose={() => setAdding(false)} onSaved={() => { setAdding(false); void reload(); }} /> : null}
  </div>;
}

function EventModal({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const [title, setTitle] = useState(""); const [date, setDate] = useState(""); const [area, setArea] = useState("family"); const [privacy, setPrivacy] = useState("private"); const [saving, setSaving] = useState(false); async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); await controlAction("create_item", { itemType: "event", title, dueDate: date, area, sensitive: privacy === "private", metadata: { calendarPrivacy: privacy === "busy" ? "busy" : "full" } }); setSaving(false); onSaved(); } return <Modal title="新增日程" onClose={onClose}><form className="grid gap-4" onSubmit={save}><label><span className="label">日程名稱</span><input className="field mt-2" value={title} onChange={(event) => setTitle(event.target.value)} required /></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">日期</span><input className="field mt-2" type="date" value={date} onChange={(event) => setDate(event.target.value)} required /></label><label><span className="label">範圍</span><select className="field mt-2" value={area} onChange={(event) => setArea(event.target.value)}><option value="work">工作</option><option value="family">家庭</option><option value="personal">個人</option></select></label></div><label><span className="label">日曆私隱</span><select className="field mt-2" value={privacy} onChange={(event) => setPrivacy(event.target.value)}><option value="private">私人</option><option value="full">分享時顯示完整內容</option><option value="busy">分享時只顯示忙碌</option></select></label><div className="flex gap-2"><Button type="submit" disabled={saving}>{saving ? "儲存中…" : "儲存"}</Button><Button type="button" variant="secondary" onClick={onClose}>取消</Button></div></form></Modal>; }
