"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, CalendarClock, CheckCircle2, Clock3 } from "lucide-react";
import { AuthGate } from "@/components/AuthGate";
import { LoadingState } from "@/components/LoadingState";
import { calculateLatestSafeStart, classifyDeadlineRisk, hkDateIso } from "@/lib/planning";
import { formatDate } from "@/lib/date";
import { useControlData } from "@/hooks/useControlData";

export default function DeadlinesPage() { return <AuthGate><DeadlinesContent /></AuthGate>; }

function DeadlinesContent() {
  const { data, loading, error } = useControlData(); const [filter, setFilter] = useState("all");
  const rows = useMemo(() => { if (!data) return []; return data.tasks.filter((task) => task.due_date && !["done","cancelled"].includes(task.status)).map((task) => { const latest = task.latest_safe_start_date || calculateLatestSafeStart(task.due_date, task.estimated_duration_days ?? 0, task.buffer_days ?? 0); const risk = classifyDeadlineRisk({ dueDate: task.due_date, latestSafeStartDate: latest, status: task.status, waitingExternal: task.status === "waiting" }); return { task, latest, risk }; }).filter((row) => filter === "all" || row.risk === filter).sort((a, b) => riskOrder[b.risk] - riskOrder[a.risk] || (a.task.due_date || "").localeCompare(b.task.due_date || "")); }, [data, filter]);
  if (loading || error || !data) return <LoadingState error={error} />;
  const today = hkDateIso();
  return <div className="space-y-5"><section><p className="eyebrow">Deadline Risk</p><h1 className="page-title mt-1">死線及最遲安全開始日</h1><p className="muted mt-2 max-w-3xl text-sm leading-6">風險以真實日期計算；Gentle Mode 只會調整文案，不會隱藏高風險。</p></section><section className="grid gap-3 sm:grid-cols-4"><Metric icon={<AlertTriangle className="h-5 w-5" />} label="已逾期" value={rows.filter((row) => row.risk === "overdue").length} tone="red" /><Metric icon={<Clock3 className="h-5 w-5" />} label="高風險" value={rows.filter((row) => row.risk === "high_risk").length} tone="amber" /><Metric icon={<CalendarClock className="h-5 w-5" />} label="需要留意" value={rows.filter((row) => row.risk === "attention").length} /><Metric icon={<CheckCircle2 className="h-5 w-5" />} label="正常" value={rows.filter((row) => row.risk === "normal").length} tone="green" /></section><section className="panel p-3"><label className="block max-w-xs"><span className="label">風險篩選</span><select className="field mt-2" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">全部</option><option value="overdue">已逾期</option><option value="high_risk">高風險</option><option value="attention">需要留意</option><option value="waiting_external">等待外部</option><option value="normal">正常</option></select></label></section><section className="grid gap-3">{rows.length ? rows.map(({ task, latest, risk }) => <article key={task.id} className="panel p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${riskTone[risk]}`}>{riskLabel[risk]}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{task.area === "work" ? "工作" : task.area === "personal" ? "個人" : "家庭"}</span></div><h2 className="mt-3 text-lg font-bold">{task.title}</h2><p className="muted mt-2 text-sm">下一步：{task.next_action || "未設定"}</p></div><dl className="grid shrink-0 grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-sm sm:min-w-72"><div><dt className="text-xs font-semibold text-slate-500">死線</dt><dd className="mt-1 font-bold">{formatDate(task.due_date)}</dd></div><div><dt className="text-xs font-semibold text-slate-500">尚餘</dt><dd className="mt-1 font-bold">{task.due_date! < today ? "已過期" : `${Math.ceil((new Date(task.due_date!).getTime() - new Date(today).getTime()) / 86400000)} 日`}</dd></div><div className="col-span-2"><dt className="text-xs font-semibold text-slate-500">最遲安全開始日</dt><dd className="mt-1 font-bold">{latest ? formatDate(latest) : "加入預計工期後計算"}</dd></div></dl></div></article>) : <div className="panel p-8 text-center text-sm text-slate-500">沒有符合此風險分類的死線。</div>}</section></div>;
}

function Metric({ icon, label, value, tone = "blue" }: { icon: React.ReactNode; label: string; value: number; tone?: "blue" | "red" | "amber" | "green" }) { const colours = { blue: "bg-indigo-50 text-indigo-600", red: "bg-red-50 text-red-700", amber: "bg-amber-50 text-amber-700", green: "bg-emerald-50 text-emerald-700" }; return <div className="panel flex items-center gap-3 p-4"><div className={`grid h-10 w-10 place-items-center rounded-xl ${colours[tone]}`}>{icon}</div><div><p className="muted text-xs font-semibold">{label}</p><p className="text-xl font-bold">{value}</p></div></div>; }
const riskOrder = { normal: 0, waiting_external: 1, attention: 2, high_risk: 3, overdue: 4 } as const;
const riskLabel = { normal: "正常", waiting_external: "等待外部", attention: "需要留意", high_risk: "高風險", overdue: "已逾期" } as const;
const riskTone = { normal: "bg-emerald-50 text-emerald-700", waiting_external: "bg-slate-100 text-slate-600", attention: "bg-amber-50 text-amber-700", high_risk: "bg-red-50 text-red-700", overdue: "bg-red-100 text-red-800" } as const;
